# Generated by Django 5.2 on 2025-06-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_time', models.DateTimeField(auto_now_add=True)),
                ('button_name', models.CharField(max_length=255)),
            ],
        ),
    ]
